### ISSUE TITLE
Redstone problem

### ISSUE THREAD

**Issue by FiveEYZ** [knoxhack/DenseMetals#1]
Version: densemetals-1.12.2-1.0.2

redstone got messed up on latest update

wrong texture and they cant be used for crafting
shift clicking a small amount to a chest that already have redstone will make them convert and vise versa 

here is the redstone drop from a dense redstone
[![Screenshot from Gyazo](https://gyazo.com/723d6e8e48f3e84be21f9c36414bd1f0/raw)](https://gyazo.com/723d6e8e48f3e84be21f9c36414bd1f0)
[![Screenshot from Gyazo](https://gyazo.com/acd18724491fb8e00d7a9cdd0f977f49/raw)](https://gyazo.com/acd18724491fb8e00d7a9cdd0f977f49)

**Comment by knoxhack** [comment]
O.O

**Comment by knoxhack** [comment]
Will look into it

**Comment by FiveEYZ** [comment]
Made the issue after only breaking redstone, so now i tested all of them. 
Here i broke one of each:
[![Screenshot from Gyazo](https://gyazo.com/89d4e3a989a12da04e485dee9240b3df/raw)](https://gyazo.com/89d4e3a989a12da04e485dee9240b3df)

**Comment by drakray** [comment]
the glitchy redstone have the meta 4

**Comment by Staegrin** [comment]
![2017-11-21_03 08 34](https://user-images.githubusercontent.com/8494635/33051246-4bc3fafc-ce69-11e7-821c-c1ad74d832ea.png)
Just to mention still a problem

**Comment by YOYOK9** [comment]
Any news on when this will be fixed? Working on a modpack and don't want to make a recipe to convert the redstones...

**Comment by ElvenChaos** [comment]
@jriwanek @knoxhack Could we please get a fix? Just change the dropped redstone from meta 4 to meta 0?

**Comment by drakray** [comment]
for a TempFix™, have 1 normal redstone in your inventory, and pick the meta4. They will stack and get the meta0. True for having meta4 in inventory and picking meta0, will convert to meta4 until stack is full

**Comment by ElvenChaos** [comment]
I've made a more permanent TempFix with [Block Drops Tweaker](https://minecraft.curseforge.com/projects/block-drops-tweaker). In the following .json file, I've fixed the drops on dense redstone, fixed the quantity dropped by dense redstone (it was wrong), as well as adjusted drop rates of each of the ores that drop items (as opposed to the ores that drop themselves). Each "gem" ore drops 3x what the base ore would drop, and fortune is factored in this time, where as fortune previously would only increase drops by ~1 per lvl, as if the ores were not dense.

If you want it, just copy+paste the [text from this gist](https://gist.github.com/ElvenChaos/18549004ffb2d8d2c089eacbab89fbfd) into the **blank** blockdrops.json file.
I apologize that the .json is all in a single line, the mod unformats it everytime I change a block/drop setting.

**Comment by jriwanek** [comment]
I'll be getting to a proper fix shortly.

**Comment by knoxhack** [comment]
https://github.com/MinecraftModDevelopmentMods/DenseMetals/commit/4dd7d5aa90d12055dfc2e4dd0585876aebe6ef6f

**Comment by knoxhack** [comment]
Fixed
