### ISSUE TITLE
World Gen Crash

### ISSUE THREAD

**Issue by Dakotaraptor** [knoxhack/DenseMetals#10]
Not 100% sure Dense Metals is the problem here (I'm running it with some other mods), but the crash log says Dense Metals has something to do with it. I've been getting this error since installing Primitive Mobs, so maybe that'll help narrow it down?

https://pastebin.com/gM4GguwW

**Comment by knoxhack** [comment]
Does this happens without Primitive m9bs?

**Comment by Dakotaraptor** [comment]
Strange, it started happening around the same time I installed Primitive Mobs, but it's happening without it. Any new chunk generation crashes the game

**Comment by knoxhack** [comment]
Probably another mod causing problems to my world gen, If you could find out what mod is that would be helpful

**Comment by knoxhack** [comment]
Oh, If you don't have Base Metals try disabling the Base Metals dense ores from the config

**Comment by Dakotaraptor** [comment]
Yep, that fixed it. Very odd, was support for Base Metals added recently? Been using the mod for months without issue. Either way, thanks for the assistance!

**Comment by knoxhack** [comment]
dang I'm pretty sure I put a fail safe for when Base Metals is not present, will double check

**Comment by knoxhack** [comment]
oh derp me, I did put a safe-fail but for the Blocks only not for the generator, will fix it on next version

**Comment by knoxhack** [comment]
oh and yeah Base Metals compat was added in version 1.1.0!

**Comment by knoxhack** [comment]
fixed https://github.com/MinecraftModDevelopmentMods/DenseMetals/commit/bdb2e6175e638f11cf74e4cf87558c1c7afa830a
