### ISSUE TITLE
[Question] UBC Compatibility : Licence ?

### ISSUE THREAD

**Issue by Aang23** [knoxhack/DenseMetals#16]
Hi, I'm [UndergroundBiomes](https://minecraft.curseforge.com/projects/underground-biomes) 's dev.
I was recently asked to add support for your ores in my mod https://github.com/Aang23/UndergroundBiomesConstructs/issues/57, but since your textures aren't overlays, I'm gonna be forced to make them overlays, and include them in my own assets folder, but before doing so, since there's no license on your repo, I wanted to be sure you were OK with that.
Note that those will only be use for compatibility purposes.

**Comment by knoxhack** [comment]
You can use them for compatibility purposes between your mod and mine 
I would love to make this mod textures overlay but I'm not familiar with that techniques.
Got any tip? Or any tutorial or example code around?
