### ISSUE TITLE
Make dense ores drop materials from Divergent Underground

### ISSUE THREAD

**Issue by Xorbah** [knoxhack/DenseMetals#18]
Title. 

Link to the Curseforge page is here -

https://minecraft.curseforge.com/projects/divergent-underground?gameCategorySlug=mc-mods&projectID=320470

I have also referenced this in their Github as well. Would be awesome to see this happen!

**Comment by cleverpanda** [comment]
This really isn't an issue for them to deal with, you've told me about it and it's my side that needs to implement

**Comment by Xorbah** [comment]
Apologies. New to using GitHub.
