### ISSUE TITLE
Drops not working fully correct

### ISSUE THREAD

**Issue by dshadowwolf** [knoxhack/DenseMetals#2]
See [BaseMetals issue 202](https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/202) - seems that some of the Dense Metals ores - like Diamond - are giving Diamond Ore instead of Diamonds. This seems to be a potential issue of balance.

As its a DenseMetals issue, really, I'm referring it here.

**Comment by knoxhack** [comment]
Already implemented
